export const trending = (req,res) => res.render("home")
export const search = (req,res) => res.send("Search Video")
export const see = (req,res) => res.send("See Video")
export const edit = (req,res) => res.send("Edit Video")
export const remove = (req,res) => res.send("Remove Video")
export const upload = (req,res) => res.send("Upload Video")
